Consolidated options documentation
mschubert/clustermq pull request #218
Opened 2020-11-13 17:05 UTC by mattwarkentin

2020-11-13 17:07 UTC, mattwarkentin commented
In some cases, I had to make a guess at what an option did, feel free to let me know where I got it wrong and I can update this PR with further commits.

2020-11-14 10:59 UTC, mschubert requested changes
That's great thank you!

I made a couple of comments so I can merge

2020-11-14 10:59 UTC, mschubert commented on vignettes/userguide.Rmd
> +- `clustermq.scheduler`
Listing: Please use single-level, one space, star as enumerator, no extra newlines to be consistent with the rest of the document (see e.g. [here](https://github.com/mschubert/clustermq/blob/master/vignettes/userguide.Rmd#L207-L209))

2020-11-14 10:59 UTC, mschubert commented on vignettes/userguide.Rmd
> +  + One of the supported `clustermq` schedulers; options are `"LOCAL"`, `"multiprocess"`, `"multicore"`, `"lsf"`, `"sge"`, `"slurm"`, `"pbs"`, `"Torque"`, or `"ssh"` (default is `qsys_default`, which
Default is the hpc scheduler that is found (in `$PATH`), otherwise `local`

2020-11-14 10:59 UTC, mschubert commented on vignettes/userguide.Rmd
> +  + Path for a file that will be created and populated with logging information regarding the SSH connection (e.g. `"~/cmq_ssh.log"`); helpful for debugging purposes
this log file is created on the ssh host, not locally (mention to void confusion)

2020-11-14 10:59 UTC, mschubert commented on vignettes/userguide.Rmd
> +  + The amount of time to wait (in seconds) after an error occurs before timing out (default is `min(timeout, 30)` seconds)
In case of a worker error, the amount of time to wait for the remaining workers to finish their computations and shut down cleanly

2020-11-14 10:59 UTC, mschubert commented on vignettes/userguide.Rmd
> +  + Path to a template file for submitting HPC jobs; only necessary if using your own template, otherwise the default template will be used (default depends on `clustermq.scheduler`)
would be nice to link to template section

2020-11-14 10:59 UTC, mschubert commented on vignettes/userguide.Rmd
> +  + A list object containing any number of `clustermq` options described above (default is an empty list (i.e. `list()`))
A named list of default template values (not for the options listed here). This takes precedence of defaults specified in the template file

2020-11-14 10:59 UTC, mschubert commented on vignettes/userguide.Rmd
> +Options can be set by including a call to `options()` in your `.Rprofile`, or by calling `options()` in a script or interactively during a session.
To avoid confusion: `options(<key>=<value>)`

2020-11-14 10:59 UTC, mschubert commented on vignettes/userguide.Rmd
> +### Options
Please make this a level-2 heading between Usage and Environments

2020-11-14 10:59 UTC, mschubert commented on vignettes/userguide.Rmd
> +The various configurable options are mentioned throughout the documentation where applicable, however, we list all of the options here for reference.
Please keep line length to 80 chrs to be consistent with the rest of the document

2020-11-16 19:35 UTC, mschubert approved these changes

2020-11-16 19:36 UTC, merged

2020-11-16 19:36 UTC, mschubert commented
Merged, thank you!